### ISSUE TITLE
Can't create or mount volumes

### ISSUE THREAD

**Issue by rsommer** [costela/docker-volume-hetzner#2]
While trying to test this, i cannot create or mount volumes.

```
$ docker volume create -d hetzner test
Error response from daemon: create test: VolumeDriver.Create: EOF
```

The plugin seems to be configures correctly, because the `ls` subcommand lists already existing hetzner volumes:

```
$ docker volume ls
DRIVER              VOLUME NAME
hetzner:latest      postgres_test
```

The log:
```
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="2019/08/14 09:22:45 Entering go-plugins-helpers capabilitiesPath" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="2019/08/14 09:22:45 Entering go-plugins-helpers getPath" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="2019/08/14 09:22:45 Entering go-plugins-helpers createPath" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="2019/08/14 09:22:45 http: panic serving @: runtime error: invalid memory address or nil pointer dereference" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="goroutine 44 [running]:" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="net/http.(*conn).serve.func1(0xc00025abe0)" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/usr/local/go/src/net/http/server.go:1746 +0xd0" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="panic(0x6b5440, 0x9396f0)" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/usr/local/go/src/runtime/panic.go:513 +0x1b9" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="main.(*hetznerDriver).Create(0xc00000c040, 0xc0003026c0, 0xc000368400, 0x68dd00)" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/plugin/driver.go:57 +0x1c5" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="github.com/docker/go-plugins-helpers/volume.(*Handler).initMux.func1(0x760cc0, 0xc0003909a0, 0xc000368400)" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/go/pkg/mod/github.com/docker/go-plugins-helpers@v0.0.0-20180917142844-39aeefe5db4e/volume/api.go:139 +0xe9" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="net/http.HandlerFunc.ServeHTTP(0xc00000ec60, 0x760cc0, 0xc0003909a0, 0xc000368400)" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/usr/local/go/src/net/http/server.go:1964 +0x44" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="net/http.(*ServeMux).ServeHTTP(0xc00004ede0, 0x760cc0, 0xc0003909a0, 0xc000368400)" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/usr/local/go/src/net/http/server.go:2361 +0x127" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="net/http.serverHandler.ServeHTTP(0xc000050f70, 0x760cc0, 0xc0003909a0, 0xc000368400)" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/usr/local/go/src/net/http/server.go:2741 +0xab" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="net/http.(*conn).serve(0xc00025abe0, 0x760e80, 0xc00003e700)" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/usr/local/go/src/net/http/server.go:1847 +0x646" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="created by net/http.(*Server).Serve" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45+02:00" level=error msg="\t/usr/local/go/src/net/http/server.go:2851 +0x2f5" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:45 dockerhost dockerd[7173]: time="2019-08-14T11:22:45.884762170+02:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f/hetzner.sock/VolumeDriver.Create: Post http://%2Frun%2Fdocker%2Fplugins%2F8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f%2Fhetzner.sock/VolumeDriver.Create: EOF, retrying in 1s"
Aug 14 11:22:46 dockerhost dockerd[7173]: time="2019-08-14T11:22:46+02:00" level=error msg="2019/08/14 09:22:46 Entering go-plugins-helpers createPath" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:46 dockerhost dockerd[7173]: time="2019-08-14T11:22:46+02:00" level=error msg="2019/08/14 09:22:46 Entering go-plugins-helpers capabilitiesPath" plugin=8065d7c1773187ab2e9c1dcee0e2e717c0966cd7c795695c6716250cc2a27f3f
Aug 14 11:22:46 dockerhost dockerd[7173]: time="2019-08-14T11:22:46.887388478+02:00" level=error msg="Handler for POST /v1.40/volumes/create returned error: create testvolume: VolumeDriver.Create: EOF\n"
```

This is on ubuntu 18.04:
```
$ docker --version
Docker version 19.03.1, build 74b1e89
```

**Comment by costela** [comment]
Is the host also called `dockerhost` on the hcloud dashboard?
If you have the `hcloud` CLI tool installed, what does `hcloud server describe dockerhost` say?
It seems a bit weird that we're getting a nil pointer. Would indicate the server doesn't have a datacenter/location. :thinking:

**Comment by rsommer** [comment]
The logfile was redacted, the logs include the FQDN of the given host instead of "dockerhost". The names in the dashboard are the shortnames. If I query the API directly, datacenter and location are present.

**Comment by rsommer** [comment]
Ok, I did change the name at hetzner's side to match the FQDN, now it's working, but it feels a bit odd to be forced to name the servers like this at the dashboard. Maybe getServerForLocalhost should try shortname and FQDN?

**Comment by costela** [comment]
@rsommer ok, so what does `hostname` and `hostname -f` say? I suspect the host might be returning its FQDN as the hostname.

It's still a bug that the driver doesn't complain more explicitly about not finding the host though. I'll look into it.

**Comment by rsommer** [comment]
Indeed, I have to investigate on that. All nodes are deployed automatically and return the shortname for `hostname` and the FQDN for `hostname -f`. But on the testing node I really get the FQDN via `hostname`, not the shortname, which explains the behaviour.
